In [1]:
import pandas as pd

In [5]:
person = {"first": ["Rishab", "Rajas", "Sam"],
          "last": ["Raina", "Raina", "Sulek"],
          "email": ["rainaa0277@gmail.com", "rajasraut@yahoo.com", "samsulek01@gmail.com"]}

In [6]:
person_df = pd.DataFrame(person)
person_df

    first   last                 email
0  Rishab  Raina  rainaa0277@gmail.com
1   Rajas  Raina   rajasraut@yahoo.com
2     Sam  Sulek  samsulek01@gmail.com

In [14]:
(person_df['last'] == 'Raina')

0     True
1     True
2    False
Name: last, dtype: bool

In [10]:
#filter people who have 'Raina' as last name
filt = (person_df['last'] == 'Raina')

In [11]:
person_df[filt]

    first   last                 email
0  Rishab  Raina  rainaa0277@gmail.com
1   Rajas  Raina   rajasraut@yahoo.com

In [15]:
person_df.loc[filt,"email"]   #loc works for boolean

0    rainaa0277@gmail.com
1     rajasraut@yahoo.com
Name: email, dtype: object

## Operators
#### & - AND
#### | - OR

In [16]:
#filter rows where last = 'Raina' and first = 'Rishab'
filt = (person_df['last'] == 'Raina') & (person_df['first'] == 'Rishab')

In [17]:
person_df.loc[filt]

    first   last                 email
0  Rishab  Raina  rainaa0277@gmail.com

In [18]:
#filter rows where last = 'Raina' OR first = 'Rishab'
filt = (person_df['last'] == 'Raina') | (person_df['first'] == 'Rishab')

In [19]:
person_df.loc[filt]

    first   last                 email
0  Rishab  Raina  rainaa0277@gmail.com
1   Rajas  Raina   rajasraut@yahoo.com

In [ ]:
#filter rows where neither last = 'Raina' nor first = 'Rishab'
filt = (person_df['last'] == 'Raina') | (person_df['first'] == 'Rishab')

In [ ]:
person_df.loc[~filt] #tilda is used for opposite condition

  first   last                 email
2   Sam  Sulek  samsulek01@gmail.com

## Back to actual data

In [27]:
#Load the datasets
df = pd.read_csv('data\survey_results_public.csv',index_col='Respondent')
schema_df = pd.read_csv('data\survey_results_schema.csv',index_col='Column')

In [41]:
df.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [29]:
#By default we can only see 20columns, let's change that to 85 so we can see all the columns
pd.set_option('display.max_columns',85)

#Similarly, we can change the maximum number of rows displayed
pd.set_option('display.max_rows',85)

In [32]:
schema_df.sort_index(inplace=True)
schema_df

                                                             QuestionText
Column
Age                     What is your age (in years)? If you prefer not...
Age1stCode              At what age did you write your first line of c...
BetterLife              Do you think people born today will have a bet...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BlockchainOrg           How is your organization thinking about or imp...
CareerSat               Overall, how satisfied are you with your caree...
CodeRev                          Do you review code as part of your work?
CodeRevHrs              On average, how many hours per week do you spe...
CompFreq                 Is that compensation weekly, monthly, or yearly?
CompTotal               What is your current total compensation (salar...
Containers              How do you use containers (Docker, Open Contai...
ConvertedComp           Salary converted to annual USD salaries using ...
Country                         In which country do you currently reside?
CurrencyDesc            Which currency do you use day-to-day? If your ...
CurrencySymbol          Which currency do you use day-to-day? If your ...
DatabaseDesireNextYear  Which of the following database environments h...
DatabaseWorkedWith      Which of the following database environments h...
Dependents              Do you have any dependents (e.g., children, el...
DevEnviron              Which development environment(s) do you use re...
DevType                 Which of the following describe you? Please se...
EdLevel                 Which of the following best describes the high...
EduOther                Which of the following types of non-degree edu...
Employment              Which of the following best describes your cur...
EntTeams                Have you ever used Stack Overflow for Enterpri...
Ethnicity               Which of the following do you identify as? Ple...
Extraversion              Do you prefer online chat or IRL conversations?
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
Gender                  Which of the following do you currently identi...
Hobbyist                                          Do you code as a hobby?
ITperson                 Are you the "IT support person" for your family?
ImpSyn                  For the specific work you do, and the years of...
JobFactors              Imagine that you are deciding between two job ...
JobSat                  How satisfied are you with your current job? (...
JobSeek                 Which of the following best describes your cur...
LanguageDesireNextYear  Which of the following programming, scripting,...
LanguageWorkedWith      Which of the following programming, scripting,...
LastHireDate            When was the last time that you took a job wit...
LastInt                 In your most recent successful job interview (...
MainBranch              Which of the following options best describes ...
MgrIdiot                How confident are you that your manager knows ...
MgrMoney                Do you believe that you need to be a manager t...
MgrWant                 Do you want to become a manager yourself in th...
MiscTechDesireNextYear  Which of the following other frameworks, libra...
MiscTechWorkedWith      Which of the following other frameworks, libra...
OffOn                         Have you tried turning it off and on again?
OpSys                   What is the primary operating system in which ...
OpenSource              How do you feel about the quality of open sour...
OpenSourcer                   How often do you contribute to open source?
OrgSize                 Approximately how many people are employed by ...
PlatformDesireNextYear  Which of the following platforms have you done...
PlatformWorkedWith      Which of the following platforms have you done...
PurchaseHow             How does your company make decisions about pur...
PurchaseWhat            What level of influence do you, personally, ha...
Respondent              Randomized respondent ID number (not in order ...
ResumeUpdate            Think back to the last time you updated your r...
SOAccount                           Do you have a Stack Overflow account?
SOComm                  Do you consider yourself a member of the Stack...
SOFindAnswer            On average, how many times a week do you find ...
SOHowMuchTime           About how much time did you save? If you're no...
SOJobs                  Have you ever used or visited Stack Overflow J...
SONewContent            Would you like to see any of the following on ...
SOPartFreq              How frequently would you say you participate i...
SOTimeSaved             Think back to the last time you solved a codin...
SOVisit1st              To the best of your memory, when did you first...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisitTo               I visit Stack Overflow to... (check all that a...
ScreenName                                           What do you call it?
Sexuality               Which of the following do you currently identi...
SocialMedia                   What social media site do you use the most?
Student                 Are you currently enrolled in a formal, degree...
SurveyEase              How easy or difficult was this survey to compl...
SurveyLength            How do you feel about the length of the survey...
Trans                                     Do you identify as transgender?
UndergradMajor          What was your main or most important field of ...
UnitTests               Does your company regularly employ unit tests ...
WebFrameDesireNextYear  Which of the following web frameworks have you...
WebFrameWorkedWith      Which of the following web frameworks have you...
WelcomeChange           Compared to last year, how welcome do you feel...
WorkChallenge           Of these options, what are your greatest chall...
WorkLoc                                   Where would you prefer to work?
WorkPlan                          How structured or planned is your work?
WorkRemote                                How often do you work remotely?
WorkWeekHrs              On average, how many hours per week do you work?
YearsCode               Including any education, how many years have y...
YearsCodePro            How many years have you coded professionally (...

In [35]:
schema_df.loc['ConvertedComp','QuestionText']

'Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 working months and 50 working weeks.'

In [47]:
#filter data for people who have salary > 70000
high_salary = df['ConvertedComp'] > 70000

In [49]:
df.loc[high_salary,['LanguageWorkedWith','ConvertedComp','Country']]

,LanguageWorkedWith,ConvertedComp,Country
Respondent,,,
6,Java;R;SQL,366420.0,Canada
9,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0,New Zealand
13,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0,United States
16,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0,United Kingdom
22,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0,United States
...,...,...,...
88876,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0,United States
88877,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0,United States
88878,HTML/CSS;JavaScript;Scala;TypeScript,130000.0,United States
88879,Bash/Shell/PowerShell;C++;Python,82488.0,Finland
88882,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0,Netherlands

In [53]:
# filter the survey results only from a list of countries

countries = ["United States", "India", "United Kingdom", "Germany", "Canada"]
filt = df['Country'].isin(countries)

In [54]:
df.loc[filt,['LanguageWorkedWith','ConvertedComp','Country']]

,LanguageWorkedWith,ConvertedComp,Country
Respondent,,,
1,HTML/CSS;Java;JavaScript;Python,NaN,United Kingdom
4,C;C++;C#;Python;SQL,61000.0,United States
6,Java;R;SQL,366420.0,Canada
8,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,NaN,India
10,C#;Go;JavaScript;Python;R;SQL,13293.0,India
...,...,...,...
85642,Go;HTML/CSS,NaN,United States
85961,C;C++;Other(s):,NaN,United Kingdom
86012,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript,NaN,India
88282,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;W...,NaN,United States
88377,HTML/CSS;JavaScript;Other(s):,NaN,Canada

In [55]:
##filter the survey results for people who have answered know 'Python as programming language

filt = df['LanguageWorkedWith'].str.contains('Python', na=False)

In [56]:
df.loc[filt,['LanguageWorkedWith','ConvertedComp','Country']]

,LanguageWorkedWith,ConvertedComp,Country
Respondent,,,
1,HTML/CSS;Java;JavaScript;Python,NaN,United Kingdom
2,C++;HTML/CSS;Python,NaN,Bosnia and Herzegovina
4,C;C++;C#;Python;SQL,61000.0,United States
5,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,NaN,Ukraine
8,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,NaN,India
...,...,...,...
84539,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,NaN,United Kingdom
85738,Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):,NaN,Brazil
86566,Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):,NaN,Switzerland
87739,C;C++;HTML/CSS;JavaScript;PHP;Python;SQL,NaN,Czech Republic
88212,HTML/CSS;JavaScript;Python,NaN,Spain

In [63]:
df.loc[8,'LanguageWorkedWith']

'Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;Python;SQL'